language: csharp
mono: 5.4.0
dotnet: 2.0.0
os:
  - linux
  - osx
sudo: false
dist: trusty
osx_image: xcode9.1

addons:
  apt:
    sources:
    packages:
script: 
  - echo "========== build all Mono samples ============"
  - msbuild /p:configuration=Debug /t:restore,compile SampleApplications/Workshop/Reference/ConsoleReferenceServer/MonoReferenceServer.csproj
  - msbuild /p:configuration=Release /t:restore,compile SampleApplications/Workshop/Reference/ConsoleReferenceServer/MonoReferenceServer.csproj
  - msbuild /p:configuration=Debug /t:restore,compile SampleApplications/Samples/NetCoreConsoleServer/MonoConsoleServer.csproj
  - msbuild /p:configuration=Release /t:restore,compile SampleApplications/Samples/NetCoreConsoleServer/MonoConsoleServer.csproj
  - echo "========== build all .Net Core samples ============"
  - dotnet restore "UA Core Library.sln"
  - dotnet restore "UA-NetStandard.sln"
  - dotnet restore "UA Global Discovery Server.sln"
  - dotnet build -c Debug SampleApplications/Samples/NetCoreConsoleClient/NetCoreConsoleClient.csproj
  - dotnet build -c Debug SampleApplications/Samples/NetCoreConsoleServer/NetCoreConsoleServer.csproj
  - dotnet build -c Release SampleApplications/Samples/NetCoreConsoleClient/NetCoreConsoleClient.csproj
  - dotnet build -c Release SampleApplications/Samples/NetCoreConsoleServer/NetCoreConsoleServer.csproj
  - dotnet restore "SampleApplications/Workshop/Aggregation/UA Aggregation.sln"
  - dotnet build -c Debug SampleApplications/Workshop/Aggregation/ConsoleAggregationServer
  - dotnet build -c Release SampleApplications/Workshop/Aggregation/ConsoleAggregationServer
  - dotnet restore "SampleApplications/Workshop/Reference/UA Reference.sln"
  - dotnet build -c Debug SampleApplications/Workshop/Reference/ConsoleReferenceServer/ConsoleReferenceServer.csproj
  - dotnet build -c Release SampleApplications/Workshop/Reference/ConsoleReferenceServer/ConsoleReferenceServer.csproj
  - dotnet build -c Debug SampleApplications/Samples/GDS/ConsoleServer
  - dotnet build -c Release SampleApplications/Samples/GDS/ConsoleServer
  - dotnet build -c Debug SampleApplications/Samples/GDS/ClientTest
  - dotnet build -c Release SampleApplications/Samples/GDS/ClientTest
  - dotnet test -c Debug --filter TestCategory!="GDSPush" SampleApplications/Samples/GDS/ClientTest
  - dotnet test -c Release --filter TestCategory!="GDSPush" SampleApplications/Samples/GDS/ClientTest
  - dotnet test -c Debug --filter TestCategory="GDSPush" SampleApplications/Samples/GDS/ClientTest
  - dotnet test -c Release --filter TestCategory="GDSPush" SampleApplications/Samples/GDS/ClientTest
  - echo "========== run .Net Core samples ============"
  - cd SampleApplications/Samples/NetCoreConsoleServer/bin/Debug/netcoreapp2.0
  - dotnet NetCoreConsoleServer.dll -t 10 -a
  - cd $TRAVIS_BUILD_DIR
  - ./testclientserver.sh

after_script:
  - echo "========== build done ============"

after_failure:
  - cd $HOME
  - cd .local/share/OPC
  - ls -R
  - cd Logs
  - cat GlobalDiscoveryTestClient.log.txt
  - cat ServerConfigurationPushTestClient.log.txt
  - cat GlobalDiscoveryTestServer.log.txt
  - cd $TRAVIS_BUILD_DIR


